from enum import StrEnum


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    INGESTING = "INGESTING"
    TRANSCRIBING = "TRANSCRIBING"
    CURATING = "CURATING"
    WAITING_SELECTION = "WAITING_SELECTION"
    RENDERING = "RENDERING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class JobType(StrEnum):
    ANALYSIS = "ANALYSIS"
    DIRECT_RENDER = "DIRECT_RENDER"


class ErrorCode(StrEnum):
    INVALID_YOUTUBE_URL = "INVALID_YOUTUBE_URL"
    YOUTUBE_DOWNLOAD_FAILED = "YOUTUBE_DOWNLOAD_FAILED"
    FFMPEG_NOT_AVAILABLE = "FFMPEG_NOT_AVAILABLE"
    AUDIO_EXTRACTION_FAILED = "AUDIO_EXTRACTION_FAILED"
    UNSUPPORTED_LANGUAGE = "UNSUPPORTED_LANGUAGE"
    TRANSCRIPTION_FAILED = "TRANSCRIPTION_FAILED"
    LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
    INVALID_LLM_OUTPUT = "INVALID_LLM_OUTPUT"
    INSUFFICIENT_CANDIDATES = "INSUFFICIENT_CANDIDATES"
    INVALID_TIME_RANGE = "INVALID_TIME_RANGE"
    INVALID_JOB_STATE = "INVALID_JOB_STATE"
    CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND"
    SUBTITLE_GENERATION_FAILED = "SUBTITLE_GENERATION_FAILED"
    VIDEO_RENDER_FAILED = "VIDEO_RENDER_FAILED"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    UPLOAD_NOT_IMPLEMENTED = "UPLOAD_NOT_IMPLEMENTED"
    SOURCE_CACHE_INVALID = "SOURCE_CACHE_INVALID"
    SOURCE_CACHE_MISSING = "SOURCE_CACHE_MISSING"
    INVALID_CACHE_TARGET = "INVALID_CACHE_TARGET"
    STORAGE_CONFLICT = "STORAGE_CONFLICT"
    MANIFEST_INVALID = "MANIFEST_INVALID"
    SOURCE_FINGERPRINT_MISMATCH = "SOURCE_FINGERPRINT_MISMATCH"
    TRANSCRIPT_CACHE_INVALID = "TRANSCRIPT_CACHE_INVALID"
    SUBTITLE_REPAIR_EXHAUSTED = "SUBTITLE_REPAIR_EXHAUSTED"
    RENDER_NOT_FOUND = "RENDER_NOT_FOUND"
    RENDER_NOT_PUBLISHABLE = "RENDER_NOT_PUBLISHABLE"
    ARTIFACT_PATH_INVALID = "ARTIFACT_PATH_INVALID"
    INVALID_PUBLISH_STATE = "INVALID_PUBLISH_STATE"
