from enum import StrEnum


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    INGESTING = "INGESTING"
    TRANSCRIBING = "TRANSCRIBING"
    CURATING = "CURATING"
    WAITING_SELECTION = "WAITING_SELECTION"
    RENDERING = "RENDERING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class JobType(StrEnum):
    ANALYSIS = "ANALYSIS"
    DIRECT_RENDER = "DIRECT_RENDER"


class ErrorCode(StrEnum):
    INVALID_YOUTUBE_URL = "INVALID_YOUTUBE_URL"
    YOUTUBE_DOWNLOAD_FAILED = "YOUTUBE_DOWNLOAD_FAILED"
    FFMPEG_NOT_AVAILABLE = "FFMPEG_NOT_AVAILABLE"
    AUDIO_EXTRACTION_FAILED = "AUDIO_EXTRACTION_FAILED"
    UNSUPPORTED_LANGUAGE = "UNSUPPORTED_LANGUAGE"
    TRANSCRIPTION_FAILED = "TRANSCRIPTION_FAILED"
    LLM_REQUEST_FAILED = "LLM_REQUEST_FAILED"
    INVALID_LLM_OUTPUT = "INVALID_LLM_OUTPUT"
    INSUFFICIENT_CANDIDATES = "INSUFFICIENT_CANDIDATES"
    INVALID_TIME_RANGE = "INVALID_TIME_RANGE"
    CANDIDATE_NOT_FOUND = "CANDIDATE_NOT_FOUND"
    SUBTITLE_GENERATION_FAILED = "SUBTITLE_GENERATION_FAILED"
    VIDEO_RENDER_FAILED = "VIDEO_RENDER_FAILED"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    UPLOAD_NOT_IMPLEMENTED = "UPLOAD_NOT_IMPLEMENTED"

